export const fieldTypes = {
  nrOfEmployees: "Antal anställda",
  expiredAgreement: "Avtal går ut",
  position: "Befattning",
  visitingAddress: "Besöksadress",
  directNumber: "Direktnummer",
  email: "E-post",
  surname: "Efternamn",
  company: "Företag",
  firstName: "Förnamn",
  itPartner: "IT-partner",
  categorization: "Kategorisering",
  currentSolution: "Nuvarande lösning",
  turnOver: "Omsättning tkr",
  orgNr: "Org nr",
  county: "Ort",
  postalAdress: "Postadress",
  postalCode: "Postnummer",
  reported: "Rapporterad",
  calledBy: "Ringd av",
  exchangeNumber: "Växelnummer",
};
